### ISSUE TITLE
RFC: lookup prebuilt releases by commit hash rather than tag

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lake#144]
I'm experimenting with the prebuilt release feature and it's really great. There's only one issue: I'd like to create a binary archive for every commit, but this means that every commit also needs a corresponding tag. Would it be possible to look up releases by commit instead of by tag?

Looking at the Github API, this is maybe not straightforward: they provide a way to get the release corresponding to a tag, but not to a commit. We could query all the releases and filter them, but that's not nice either.

**Comment by tydeu** [comment]
Is it really worthwhile to have a prebuilt release for every commit? I would suggest building nightlies and using a scheduled GitHub action to generate a tag and release every night for the latest commit.

**Comment by JLimperg** [comment]
Since Lean dependency management is based on commit hashes atm, it would be nice to guarantee that the specific commit used by a dependent project has a prebuilt release. But mathlib now uses a different mechanism to cache build artifacts, including dependencies, so this is even less urgent than before.

**Comment by tydeu** [comment]
The Lake repository is being deprecated and its issues transferred to [leanprover/lean4](https://github.com/leanprover/lean4). As this issue is stale and while likely be addressed in more broad-scoped fashion via a Lake-based successor to `lake exe cache`, I am closing it instead of transferring it. Feel free to reopen a similar issue over on [leanprover/lean4](https://github.com/leanprover/lean4).
