### ISSUE TITLE
Reproducible content and input addressable builds

### ISSUE THREAD

**Issue by Anderssorby** [leanprover/lake#145]
To achieve better cachability and reproducability as well as a native integration with nix builds each build step should be completely described by it's input has so that in a sandboxed environment it would always produce the same result and that. This would in turn generate a Merkle tree of the build allowing for much more efficient caching and reproducability.

This can in turn be used as a plug-in to the nix ecosystem. 

The buildLeanPackage.nix setup is already doing this, but it lacks in good UI, flexibility and native interoperability with Lean. By combining the two we could get the best of both worlds without having to maintain both systems.

**Comment by tydeu** [comment]
The Lake repository is being deprecated and its issues transferred to [leanprover/lean4](https://github.com/leanprover/lean4). As this issue is stale and does not have any directly actionable items, I am closing it instead of transferring it. Feel free to reopen a similar issue over on [leanprover/lean4](https://github.com/leanprover/lean4).
