### ISSUE TITLE
Error when importing dependencies with precompiled modules

### ISSUE THREAD

**Issue by arthurpaulino** [leanprover/lake#146]
Zulip thread: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/error.20loading.20library.20Aesop-Nanos.2Edll/near/316529638

Apparently it can't find `.so`/`.dll` files from libs with precompiled modules.

In our case, it wasn't being able to find `librust_ffi.so` so we [disabled `precompileModules`](https://github.com/yatima-inc/YatimaStdLib.lean/commit/704823e421b333ea9960347e305c60f654618422)

**Comment by tydeu** [comment]
@arthurpaulino Your issue might actually be different from the on reported on Zulip.  That one is a bug with building modules with precompiled imports *without* an FFI library, It was also on Windows. What OS did your bug emerge on?

**Comment by arthurpaulino** [comment]
Ubuntu 22.04

**Comment by tydeu** [comment]
@arthurpaulino Ah, okay. That is a different bug. The problem is that on Linux you have to store external FFI libraries in the packages `libDir` (e.g. `build/lib`) or in a system library directory since Linux looks for linked dependencies of shared libraries (such as precompiled module dynlibs) in the system library path before loading them.

**Comment by arthurpaulino** [comment]
Oh, I see. Thanks for the explanation.
Can Lake be more aware of where lib files are being placed at so it's not so restrictive to a specific directory inside the package?

**Comment by tydeu** [comment]
@arthurpaulino this is not a Lake limitation but  a Linux and Lean server one. On other OSes they can be wherever and everything will work fine. The problem is that Lake as no way to change the Lean server environment variables from `print-paths` so build results have to be found somewhere in the Lean server's library path. We can augment this when the server is started in `lake serve`, which is how `build/lib` ends up in the path, but it currently can't be updated later (i.e., after a build).

This could potentially be solved with an update to the Lean server that added another field to `print-paths` results that update system environment variables after a build.

**Comment by Kha** [comment]
@arthurpaulino The proper Linux solution would be to either directly link against a path instead of a `-l` library name (with the usual caveats for relative paths), or to embed the directory path with `-Wl,-rpath`.

**Comment by tydeu** [comment]
@Kha Could Lake do that i.e. link with a full path instead of `-l` for precompile modules? Or does doing so embed the full path in the library and break the shared library if dependency is relocated (which could be a major problem for cloud builds)? I seem to remember it being the later, but I am not sure.

**Comment by Kha** [comment]
If you give it a path, it gets embedded as is, yes. I would say relocation is difficult in any case, but with relative paths it should at least be feasible.
A simpler solution might be to symlink external dependencies into the build dir for development and copy them in for deployment.
