### ISSUE TITLE
Instructions to include mathlib

### ISSUE THREAD

**Issue by PatrickMassot** [leanprover/lake#150]
The README says that math project should be created using `lake new <package-name> math` but this doesn't work. First it doesn't build at all because it doesn't make sure the lean-toolchain is the same as mathlib. And then it doesn't get oleans for mathlib.

**Comment by tydeu** [comment]
Yeah, all `lake new <pkg> math` does is add mathlib to the Lakefile as a dependency. I do not know how mathlib is currently distributing oleans. If someone from the mathlib community wants to help / PR some updates to either or the code to create a smoother experience, I would be more than happy to accommodate them.

**Comment by arthurpaulino** [comment]
`lake new/init ... math` is fixed. As for downloading oleans, I would strongly advise against that without a native Lake solution for hosting cache files.

That would be properly implemented in a two step process: one for revamping `lake build` and then a new `lake cache` for hosting build files. I'll write an RFC for it.

**Comment by tydeu** [comment]
@arthurpaulino Fyi, there already is a native Lake solution for caching builds: `lake upload` (see [this section](https://github.com/leanprover/lake#github-release-builds) in the README)

**Comment by arthurpaulino** [comment]
The solution implemented in `mathlib4` is more efficient because it works on a per-file basis. Each file has its own hash, similar (maybe semantically equivalent, even) to the Lake traces. So if a leaf file is changed, it won't pack the whole thing. It will upload a single file and if someone already had the previous cache files, it will download a single file when requested.

**Comment by tydeu** [comment]
As Arthur mentioned, part 1 of this issue was addressed back in #152. Now, part 2 will hopefully be addressed by [mathlib4#6603](https://github.com/leanprover-community/mathlib4/pull/6603). Thus, if [mathlib4#6603](https://github.com/leanprover-community/mathlib4/pull/6603) (or a similar approach) is merged, I will close this issue. Does that seem reasonable, @PatrickMassot?
