### ISSUE TITLE
Redundant lean installs

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lake#39]
Bootstrap results in redundant lean versions being installed.  The vscode extension runs ` elan-init.ps1 -y leanprover/lean4:nightly ` and when the user next does `lake init foo`, lake installs leanprover--lean4---nightly-2021-12-13 even though the default toolchain has an identical version as shown below:
```
>c:\users\clovett\.elan\toolchains\leanprover--lean4---nightly\bin\lean --version
Lean (version 4.0.0-nightly-2021-12-13, commit 3a6cc774241b, Release)

>c:\users\clovett\.elan\toolchains\leanprover--lean4---nightly-2021-12-13\bin\lean --version
Lean (version 4.0.0-nightly-2021-12-13, commit 3a6cc774241b, Release)
```

**Comment by tydeu** [comment]
@lovettchris Very true. However, this is entirely due to elan, It has nothing to do with Lake. You should raise this issue over at [leanprover/elan](https://github.com/leanprover/elan) instead.

**Comment by tydeu** [comment]
@lovettchris  Ah, having looked over your comment in the linked issue, I see where your confusion it coming from. When Lake creates a new package it pins the package to its specific version of Lean (i.e, `nightly-2021-12-13` in this example) -- not its general toolchain (i.e., `nightly`) --by writing that version to `lean-toolchain`. This is the desired behavior -- packages should be pinned to a specific version of Lean and not a distro to make builds easily reproducible. 

However, because of the way elan works,  when a Lean tool is then run in that folder, elan downloads that specific toolchain (if it is not already installed) instead of currently using the distro (even though the versions match). I do not know why this decision was made, you can probably ask @Kha,  but I would suspect it makes toolchain management easier.
