### ISSUE TITLE
Cannot run `lake env` in parallel

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#63]
Some (but not all) processes exited with the following error:
```
info: lean3port: trying to update ./lean_packages/lean3port to revision 9fa58e0bd55598945f81692645534a40862c5cfd
error: git exited with code 128
```

This is because git refuses to run in parallel (for understandable reasons):
```
$ git checkout --detach HEAD & git checkout --detach HEAD
[1] 2278244
fatal: Unable to create '/home/gebner/lake/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
HEAD is now at d961d8c chore: update Lean version
[1]+  Exit 128                git checkout --detach HEAD
```

The bug presumably also causes a race condition when opening multiple files at once in the editor.

**Comment by tydeu** [comment]
This does not seem ideal, but I am not sure how to fix it. Invoking `git` seems to be necessary if we want `lake env` to download and/or update dependencies.  What ideas do  you have for a fix?  

One solution I can think of would be to remove such functionality from `lake env` (e.g., to relegate it to `lake configure` or `lake build`). Alternatively, Lake could skip updating repositories with an active `git` process (i.e., with a `.git/index.lock` file) under the assumption it is due to another active Lake process, but that seems likely to generate confusion (i.e., when a non-Lake `git` process unexpected prevents Lake from updating dependencies properly).

**Comment by gebner** [comment]
> What ideas do you have for a fix?

The only bad command here is `git checkout --detach`, because *modifies* the repo.  Git commands that only read the repo are fine to execute in parallel.  So a partial fix for the issue is to avoid calling `git checkout` unless necessary, see PR #64.  This is not a full fix, since it will still break when `git checkout` is necessary.

> One solution I can think of would be to remove such functionality from `lake env`

I don't have a strong opinion here.  But it doesn't make much sense to have `lake env` update the dependencies when it doesn't build anything.

However, even if we simplify `lake env` this still leaves `lake print-paths` which has the same issue.

Longer term, I think the only proper fix is to either a) reduce the number of Lake processes (i.e., remove print-paths and put it into the server), or b) add lock files for the repositories.

> Alternatively, Lake could skip updating repositories with an active git process

This will also break when Lake is run in parallel, because the second Lake process will see the old dependency version.

**Comment by tydeu** [comment]
Oops, apparently I improperly formatted the issue reference in the commit. 1a707e6 closes this.
