### ISSUE TITLE
No warning if branch in lakefile and manifest differ

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#85]
1. Add `require a from git "../a.git"@"master"` to the lakefile.
2. Run `lake update`.
3. Change to `require a from git ".../a.git"@"develop"`.
4. Run `lake build`.

Then `lake build` will happily use the old version of `a` from the master branch in step 4, without printing a single warning.

I'm not sure what the best solution here would be.  A warning will be lost in the inevitable barrage of build errors.  Different dependencies might refer to different branches (or explicit revisions), so a fatal error is maybe too much.

This trips me up all the time now.  A compounding issue is that `lean_packages/manifest.json` was gitignored in older repositories, and so it's very easy to end up in a situation where the manifest is not checked in and you get nonreproducible errors due to different manifests on different machines.

**Comment by Kha** [comment]
Nix will automatically reset the lockfile entry if the "input descriptor" in flake.nix changed (i.e. switch everything to `develop` in this case), I found that behavior quite reasonable.

**Comment by tydeu** [comment]
@gebner 

A question that occurred to me today about this:

> A compounding issue is that `lean_packages/manifest.json` was gitignored in older repositories, and so it's very easy to end up in a situation where the manifest is not checked in and you get nonreproducible errors due to different manifests on different machines.

Lake currently uses the top-level manifest to lock dependencies. So it should not matter if nested dependencies did not check in their manifest as long as the top-level one (i.e., your project) has checked its manifest in?

**Comment by gebner** [comment]
Right, but I have more top-level projects than nested dependencies, and thus a lot of projects where a need to remember to unignore/add the manifest. :smile:

**Comment by tydeu** [comment]
I was working on this issue today and realized that we hadn't come to a conclusion as to what the solution should be. @gebner, @Kha what is the desired behavior here. A warning, an automatic update of the manifest, or something else?

**Comment by tydeu** [comment]
Currently, I have implemented a warning. While as @gebner mentioned it can be lost in a barrage of build errors, it does appear at the very top of the log so it may stand out.

**Comment by Kha** [comment]
Hmm, is there a use case where enforcing the lakefile branch would be wrong? I guess doing manual changes to the checkout? I did that before and I felt bad for doing it, but it admittedly is convenient.

**Comment by tydeu** [comment]
@Kha I think both approaches make sense. I stuck with the warning because it mirrors the current behavior for other mismatches (e.g., change in URL). If we decided to force update it here, we should probably force it in those cases as well. 

One reason to stick with the warnings is that since the manifest is likely to undergo manual modifications in some cases (e.g., to fix version conflicts), it makes sense to avoid automatically update it unless requested (e.g., via `lake update`) to avoid clobbering user changes. However, version control may be sufficient to recover from that and the automatic updates can be more convenient, so I can see arguments for both approaches.
