### ISSUE TITLE
`precompileModules` LSP error

### ISSUE THREAD

**Issue by xubaiw** [leanprover/lake#93]
When using the new `precompileModules` feature of lake, the LSP gives the error of 

```sh
error loading library, Foo: cannot open shared object file: No such file or directory
```

where Foo is a `lake new` template with `precompileModules = true`

**Comment by xubaiw** [comment]
Both in neovim and vscode.

If open LSP without running `lake build`, the error is like:

```
`/home/xubaiw/.elan/toolchains/leanprover--lean4---nightly-2022-07-03/bin/lake print-paths Init Lean Foo` failed:

stderr:
info: > LEAN_PATH=./build/lib LD_LIBRARY_PATH=/home/xubaiw/.elan/toolchains/leanprover--lean4---nightly-2022-07-03/lib:./build/lib /home/xubaiw/.elan/toolchains/leanprover--lean4---nightly-2022-07-03/bin/lean ./././Foo.lean -R ././. -o ./build/lib/Foo.olean -i ./build/lib/Foo.ilean -c ./build/ir/Foo.c
info: > /home/xubaiw/.elan/toolchains/leanprover--lean4---nightly-2022-07-03/bin/leanc -c -o ./build/ir/Foo.o ./build/ir/Foo.c -O3 -DNDEBUG
error: stderr:
In file included from ./build/ir/Foo.c:4:
/home/xubaiw/.elan/toolchains/leanprover--lean4---nightly-2022-07-03/include/lean/lean.h:8:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 error generated.
error: external command /home/xubaiw/.elan/toolchains/leanprover--lean4---nightly-2022-07-03/bin/leanc exited with status 1
error: build failed
```

After manually running `lake build`, the error is like:

```
error loading library, Foo: cannot open shared object file: No such file or directory
```

**Comment by tydeu** [comment]
The first LSP error (the `#include <stddef.h>` one) is due to `LEAN_CC` being set in the server environment (as I mention in leanprover/lean4#1281). The second issue (the `error loading library`) is due to `PATH`/`LD_LIBRARY_PATH`/`DYLD_LIBRARY_PATH` NOT being set in the server environment. I will fix the later posthaste. The former, however, I feel would be best fixed in `leanc`. For that, we will see what the @Kha and the devs thinks over in leanprover/lean4#1281.
